class BurcOzellik {
  static const String APP_NAME = "Burç Özellikleri";

  static const List<String> Burc_ad = [
    "KOC",
    "BOGA",
    "İKİZLER",
    "YENGEC",
    "ASLAN",
    "BASAK",
    "TERAZİ",
    "AKREP",
    "YAY",
    "OGLAK",
    "KOVA",
    "BALIK"
  ];
  static const List<String> Burc_tarih = [
    "21 Mart - 20 Nisan",
    "21 Nisan - 20 Mayıs",
    "21 MAyıs - 21 Haziran",
    "22 Haziran - 22 Temmuz",
    "23 Temmuz - 22 Ağustos",
    "23 Ağustos - 22 Eylül",
    "23 Eylül - 22 Ekim",
    "24 Ekim - 21 Kasım",
    "22 Kasım - 21 Aralık",
    "22 Aralık - 19 Ocak",
    "20 Ocak - 18 Şubat",
    "18 Şubat - 20 Mart"
  ];

  static const List<String> Burc_resim = [
    "koc1.jpg",
    "boga2.png",
    "ikizler3.png",
    "yengec4.png",
    "aslan5.png",
    "basak6.png",
    "terazi7.png",
    "akrep8.png",
    "yay9.png",
    "oglak10.png",
    "kova11.png",
    "balık12.png"
  ];

  static const List<String> Burc_ozellik = [
    "Burçlar üç farklı niteliğe göre gruplanır: Kardinal (öncü), değişken ve sabit burçlar. Koç burcu dört kardinal burçtan biridir. Bu burçlar mevsimleri başlatır. Koç, baharı; Yengeç, yazı; Terazi, sonbaharı; Oğlak ise kışı başlatır. Bu burçlar özgün olmayı severler ve yaptıkları her şeyde birinci olmayı isterler. "
        "Akım belirleyicidirler; arkadaş ortamlarında partileri, organizasyonları onlar başlatan onlardır.Zodyak’ın ilk burcu olan Koç burcunun varlığı her zaman enerjik ve çalkantılı bir başlangıca işaret eder. Koç burçları çalışma ortamlarında da arkadaş ortamlarında da her zaman hareket, hız ve rekabet peşindedir; her şeyde birinci olmaya çalışırlar. "
        "Yönetici gezegenleri Mars’ın ateş elementine ait olması nedeniyle Koç burcu en aktif burçlardan biridir. Zaman zaman düşünmeden de olsa harekete geçmek onların doğasındadır."
        "Güneş, Koç burcuna olağanüstü organizasyon becerileri verir: Öğlen arasından önce tek seferde birden fazla işi bitirmeyi beceremeyen bir Koç burcuyla karşılaşma ihtimaliniz düşüktür. Amaçları için mücadele etmeyi görev edinir, birlikteliğe ve takım çalışmasına önem verirler."
        "Koç burcu insan vücudunda başı yönetir ve başla birlikte harekete geçer. Kelimenin tam anlamıyla başları dik yürürler. Doğal olarak cesurdurlar ve bir şeyi denemekten ya da risk almaktan nadiren korkarlar. Hangi yaşta olursalar olsunlar bir gencin gücüne ve enerjisine sahip olurlar; verilen herhangi bir görevi çabucak yerine getirirler",
    "Burçlar üç farklı niteliğe göre gruplanır: kardinal (öncü), değişken ve sabit burçlar. Boğa burcu dört sabit burçtan biridir; diğer dört sabit burç ise Aslan, Akrep ve Kova’dır. Bu burçlar her mevsimin ortasına denk gelir. Bunlar dengeleyici burçlardır; kendilerine bir amaç belirler ve sonra da inşa etmeye başlarlar. Öncü burçların öne attığı heyecanlı fikirleri alır, bunları somut bir şeye dönüştürürler."
        "Boğa burcu toprak elementi altında gruplanan üç burçtan biridir (diğerleri Başak ve Oğlak’tır). Zodyak döngüsündeki ilk toprak burcu olduğu için binayı oluşturan temel gibidir. Çoğu Boğa insanı dengeleyicidir, kendileri ve başkaları için güvenliği sağlamaya çalışırlar. Meseleleri ayakları yere basan, pratik ve gerçekçi bir bakış açısıyla görmeye meyillidirler. Boğa burcu için para kazanmak kolaydır ve yıllarca aynı proje üzerinde çalışabilirler."
        "Hantal ve inatçı bir burç olan Boğa burcu enerjisinin iki farklı hızı vardır: Ya çayırda otlayan bir öküz gibi gevşemiş bir haldedir ya da boğa güreşindeki bir boğa gibi coşkulu. Boğa burcu içsel bir enerji tasarrufu programına sahiptir. Eğer bir şey zaman ve kaynak yatırımına değerse sabırlı bir şekilde ona ulaşır. Yaptığı işi küçük aşamalara bölmeyi sever."
        "Her ne kadar inatçılıkları olumsuz yanları olsa da bu inatçılıkları bağlılık olarak da adlandırılabilir; her ne olursa olsun görevleri yerine getirme yetenekleri muazzamdır. Bu da onları harika çalışanlar yapan bir özelliktir. Ayrıca uzun süreli arkadaşlık ve sevgililik de Boğa burcunun özelliğidir."
        "Boğa burcunun yönetici gezegeni aşkın, cazibenin, güzelliğin, tatminin, yaratıcılığın ve kadirşinaslığın gezegeni olan Venüs’tür. Boğa burçları sadıktır ve ani değişiklikleri, eleştirileri sevmezler. e sahip olurlar; verilen herhangi bir görevi çabucak yerine getirirler",
    "Burçlar üç farklı niteliğe göre gruplanır: kardinal (öncü), değişken ve sabit burçlar. İkizler burcu dört değişken burçtan biridir (diğerleri Başak, Yay ve Balık’tır). Değişken burçlar mevsimleri sona erdiren burçlardır ve her mevsimden dersler almışlardır. Her şeyin bir sonu olduğunu bilirler ve görevleri herkesin mevsim değişimine uyum sağlamasına yardımcı olmaktır. "
        "Diğer burçlardan daha bilgedirler. Diğer burçlara göre değişime daha kolay ayak uydurabilirler; pek çok duruma uyum sağlamak için bukalemun gibi renk değiştirirler. Ayrıca Zodyak’ın düzeltmenidirler: Kardinaller bir plan öne sürer, sabit burçlar planı eyleme döker, değişken burçlar ise eleştirel bir gözle son rötuşları yapar."
        "Zodyak’ta hava elementine sahip olan ilk burç İkizler olduğu için İkizler burcu, değişim ve iletişim rüzgârlarını başlatan ilk rüzgâr gibidir. İkizler burcu, büyük ve yaratıcı bir sinerji oluşturarak bir anda insanları iletişime geçirir. İkizler burcu gezegen döngüsündeyken hepimiz arkadaşlarımızla daha fazla zaman geçirmeye meyilli oluruz."
        "Enerjisi hızlı ve telaşlıdır. İkizler burcu iletişimi yönetir; esprili kelime oyunlarına, dinamik diyaloglara ilham verir. İkizler burcu geçişleri beyin fırtınaları ve sosyalleşme açısından harika bir dönemdir. Ayrıca bu burç, fikirlerin buluşmasından yanadır. İkizler burcu gezegen geçişi sırasında konuşma yetilerimiz gelişir; arkadaşlarımızla saatler boyunca o konudan bu konuya konuşurken bulabiliriz kendimizi. ",
    "Öte yandan hayatın inişli çıkışlı yönünü temsil eder; ayak uydurmayı becerebilirseniz müthiş bir heyecan yaşamış olursunuz."
        "Burçlar üç farklı niteliğe göre gruplanır: kardinal (öncü), değişken ve sabit burçlar. Yengeç burcu dört kardinal burçtan biridir. Bu burçlar mevsimleri başlatır. Koç, baharı; Yengeç, yazı; Terazi, sonbaharı; Oğlak ise kışı başlatır. Bu burçlar özgün olmayı severler ve yaptıkları her şeyde birinci olmayı isterler. Akım belirleyicidirler; arkadaş ortamlarında partileri, organizasyonları onlar başlatır."
        "Yengeç burcu, tıpkı Akrep ve Balık gibi su elementine bağlıdır. Zodyak’ın ilk su burcu olduğu için, duygu denizinin ve yaratıcı suların akmasını sağlayan bir nehir gibidir. Yengeç burcu insanları etrafındaki herkesin mutlu olmasını ister. Yengeç gezegen döngüsü etkisi altındayken ailemizle ve sevdiklerimizle vakit geçirme ihtiyacı hissederiz."
        "Duyguları ve kalpleri tarafından yönetilen Yengeçler kalabalığa karışmakta güçlük çekerler. Yengeç burcu Dünya’ya en yakın, duygularımızı en çok etkileyen, iç benliğimizi yöneten, derin arzularımızı ve duygusal isteklerimizi ortaya çıkaran bir gök cismi olan Ay tarafından yönetilir; Ay döngüsünün fazları Yengeçlerin içsel gizemlerini derinleştirir ve onların kontrolü dışında, kısa süreli duygusal örüntüler yaratır."
        "Hayatlarının ileriki dönemlerinde ruhsal çalkantılar nedeniyle sabırsızlık, sevgisizlik, bencillik, kendine acıma veya manipülasyon gibi huylar ortaya çıkabilir. Öte yandan hayatlarından memnun oldukları dönemlerde başkalarına yardım etmeyi, çatışmadan kaçınmayı severler.",
    "Burçlar üç farklı niteliğe göre gruplanır: kardinal (öncü), değişken ve sabit burçlar. Aslan burcu dört sabit burçtan biridir; diğer dört sabit burç ise Boğa, Akrep ve Kova’dır. Bu burçlar her mevsimin ortasına denk gelir. Bunlar dengeleyici burçlardır; kendilerine bir amaç belirler ve sonra da inşa etmeye başlarlar. Öncü burçların öne attığı heyecanlı fikirleri alır, bunları somut bir şeye dönüştürürler."
        "Aslan burcu ateş elementiyle yönetilen üç burçtan biridir (diğer ikisi Koç ve Yay’dır). Zodyak’ın ikinci ateş burcu Aslan olduğu için, Aslan burcunun sıcaklığı, bir kıvılcımı herkesin hissettiği büyük bir yangına dönüştürür. Pek çok Aslan burcu doğuştan sanatçı ve liderdir. Aslan burcu gezegen döngüsünün etkisi altındayken hepimiz sahne ışıklarını üzerimize çekme arzusuyla yanıp tutuşuruz. Aynı zamanda insanların damarına basan, fazla talepkâr, patronluk taslayarak insanları çıldırtan kişilere dönüşebiliriz."
        "Ateş elementine bağlı olan Aslan burcu cana yakın ve hayat doludur; her zaman gülmeye ve güzel zaman geçirmeye çalışır. En zor problemleri bile çözebilecek bir zekâya sahip olabilen Aslan burcu pek çok karmaşık durumun çözümünde kolaylıkla inisiyatif alır. Evrenimizin merkezinde duran Güneş tarafından yönetilen Aslanlar öz farkındalık arayışı içindedirler ve egoları sürekli olarak büyür (Güneş de egoyu ve maskülen enerjiyi temsil etmektedir)."
        " Arzularının ve kişiliklerinin farkında oldukları için ihtiyaç duydukları her şeyi kolayca isteyebilirler ama bir o kadar kolayca da başka insanların ihtiyaçlarını görmezden gelebilirler. Bir Aslan burcu kazanımlarına ve diğer insanların bu kazanımları nasıl gördüğüne çok kafayı takarsa kolay lokma haline gelir, çabucak alaşağı edilebilir.",
    "Burçlar üç farklı niteliğe göre gruplanır: kardinal (öncü), değişken ve sabit burçlar. Başak burcu dört değişken burçtan biridir (diğerleri İkizler, Yay ve Balık’tır). Değişken burçlar mevsimleri sona erdiren burçlardır ve her mevsimden dersler almışlardır. Her şeyin bir sonu olduğunu bilirler ve görevleri herkesi mevsim değişimine uyum sağlamalarına yardımcı olmaktır. Diğer burçlardan daha bilgedirler. Diğer burçlara göre değişime daha kolay ayak uydurabilirler; pek çok duruma uyum sağlamak için bukalemun gibi renk değiştirirler. "
        "Ayrıca Zodyak’ın düzeltmenidirler: Kardinaller bir plan öne sürer, sabitler planı eyleme döker, değişkenler ise eleştirel bir gözle son rötuşları yapar."
        "Başak burcu toprak elementiyle yönetilen üç burçtan biridir. Diğer toprak burçları ise Boğa ve Oğlaktır. Başak burcu Zodyak’taki ikinci toprak burcu olduğu için Boğa’nın işi bıraktığı yerden devralır ve hızlıca kusursuz inşa bir planı yaparak Boğa’nın attığı sağlam temeller üzerinde yükselir. Başak burcu gezegen döngüsü sırasında ayrıntılar içinde ilahi olanı çabucak tespit eder, santim santim eksiksiz bir plan hazırlar ve hedeflerimizi yerine getiririz. Başak enerjisi bizi yeni bir çalışma rutini denemeye ya da o güne kadar benimsediğimiz sistemi yenilemeye teşvik eder."
        "Ayrıca insanları gelecek konusunda endişeli (hatta evhamlı) hale getirebilir. Başak burcu gezegen geçişleri sırasında “ya öyle olursa”lara takılıp kalabiliriz."
        "Başak’ın Boğa ve Oğlak’ın arasında bir toprak burcu olması onu güçlü ama muhafazakâr bir kişi olmaya iter. Gündelik hayatında düzenli ve pratiktir. Hayatları alt üst olduğu zaman bile düzenli bir hayat sürdürürler, hedefleri ve hayallerine bağlı kalırlar. Telafi edilmesi mümkün olmayan bir ayrıntıyı kaçırdıklarından sürekli endişe ettikleri için ayrıntılar içinde kaybolabilir, aşırı eleştirel olabilir ve diğer insanların pek önemsemediği meselelere kafa yorabilirler.",
    "Burçlar üç farklı niteliğe göre gruplanır: kardinal (öncü), değişken ve sabit burçlar. Terazi burcu dört kardinal burçtan biridir. Bu burçlar mevsimleri başlatır. Koç, baharı; Yengeç, yazı; Terazi, sonbaharı; Oğlak ise kışı başlatır. Bu burçlar özgün olmayı severler ve yaptıkları her şeyde birinci olmayı isterler. Akım belirleyicidirler; arkadaş ortamlarında partileri, organizasyonları onlar başlatır."
        "Terazi burcu hava elementi ile yönetilen üç burçtan biridir. Diğerleri ise İkizler ve Kova’dır. Terazi burcu ikinci hava burcu olduğu için, İkizler’in başlattığı iletişim rüzgarlarını nezaket, görgü ve toplumsal bağ rüzgarlarına dönüştürür. Ama Terazi burcunun rüzgarları fırtına gücünde değildir; değişim rüzgarlarını o kadar nazik ve yumuşak bir şekilde getirir ki başka bir noktaya ulaştığınızı güçbela anlarsınız. "
        "Hava elementinin özü iletişim ve zekâdır; fikirlerin yayılmasına yardımcı olur. Terazi’nin kişiler arası anlayış gücü de buna eklendiğinde, bağlılıklar, faydalı diyaloglar, başarılı ilişkiler ortaya çıkar. Terazi burcu gezegen geçişi sırasında, tek başımıza yapmayı beceremediğimiz görevleri yapabilmek için kendimize bir eş arayışı içine girebiliriz. Yönettiği burçlara keskin bir zeka veren hava elementi tarafından yönetilen Terazi burcu, güzel kitapları, bitmek bilmez tartışmaları ve söyleyecek çok şeyi olan insanları sever. "
        "Terazi burcunun yönetici gezegeni Venüs bu burcun insanlarının harika sevgililer olmalarını sağlasa da diğer yandan da onları pahalı, maddi değeri yüksek şeylere de düşkün kılar.",
    "Burçlar üç farklı niteliğe göre gruplanır: kardinal (öncü), değişken ve sabit burçlar. Akrep burcu dört sabit burçtan biridir; diğer dört sabit burç ise Boğa, Aslan ve Kovadır. Bu burçlar her mevsimin ortasına denk gelir. Bunlar dengeleyici burçlardır; kendilerine bir amaç belirler ve sonra da inşa etmeye başlarlar. Öncü burçların öne attığı heyecanlı fikirleri alır, bunları somut bir şeye dönüştürürler."
        "Akrep burcu su elementine bağlı üç burçtan biridir (diğerleri Yengeç ve Balık’tır). Akrep Zodyak’ın ikinci su burcudur. Görevi kendisinin ve başkalarının duygularını güçlendirmek ve kalıcı hale getirmektir. Diğer su grubu burçları gibi akrep de duyguları deneyimlemek ve ifade etmek için yaşar ancak duygulara çok önem verse de dışarıdan belli etmemesi ile diğer su gruplarından farklıdır. Akrep burcunun pek çok sırrı vardır ve daima sırlarını başkalarından saklayarak yaşar."
        "Akrep burçları tutkulu ve iddialı kişilerdir. Gerçeği öğrenene kadar araştırmak en belirgin özelliklerindendir. Kararlı ve belirleyicidirler. Gerçeğin daima farkında olan ve hayallerden ziyade hedeflere odaklanan akrepler evrenin kurallarını çok iyi bilirler. Bu nedenle başkaları tarafından genellikle sert ve şiddetli bulunurlar ancak bu gerçekçi tutum onlara doğal bir şekilde öne çıkmalarını sağlayan liderlik özelliği verir.",
    "Yay burcu, ateş elementiyle yönetilen üç burçtan biridir (diğer iki ateş burcu Koç ve Aslan’dır). Yay burcu üçüncü ve sonuncu ateş burcu olduğu için Koç ve Aslan burcunun yarattığı liderlik ateşini dizginleyerek evrensel bir bilgi ve eylem süpernovasına dönüştürür. Zodyak’ın en ilham verici ve iyimser burcu olan Yay burcu bizi meselelerin üstesinden gelmeye ve sınırsız olasılıkların peşinden gitmeye zorlar. Yay burcu gezegen geçişi sırasında seyahat etmeye, öğrenmeye, kültürler arası bağlantı kurup ufkumuzu genişletmeye istekli olabiliriz. Diğer ateş burçları gibi Yay burcunun da sürekli olarak dünyayla temas halinde olması gereklidir."
        "Yay burcunun yönetici gezegeni, güneş sistemimizin en büyük gezegeni Jüpiter’dir. Bu nedenle bu burcun insanları “hayatın kendisinden daha büyük” olabilirler. Nasıl ki Jüpiter gezegenler arasında gaz devlerinden biriyse, kendinden çok emin olan Yay enerjisi de zaman zaman hava gazıyla dolu görünebilir. Bir şey hakkında düşünmeden üzerine atlamak Yay burcunun âdetlerinden biridir. Neyse ki Jüpiter şans getirir ve ayaklarımızı yere sağlam basmamızı sağlar. Yay insanları her şeyin en büyüğünü ve en iyisini isterler; öyle ki zaman zaman aşırıya kaçabilirler. Sınırsız hedonizm ve rahatına düşkünlük, Yay enerjisini kötü bir enerjiye dönüştürebilir.",
    "Burçlar üç farklı niteliğe göre gruplanır: kardinal (öncü), değişken ve sabit burçlar. Yengeç burcu dört kardinal burçtan biridir. Bu burçlar mevsimleri başlatır. Koç, baharı; Yengeç, yazı; Terazi, sonbaharı; Oğlak ise kışı başlatır. Bu burçlar özgün olmayı severler ve yaptıkları her şeyde birinci olmayı isterler. Akım belirleyicidirler; arkadaş ortamlarında partileri, organizasyonları onlar başlatır."
        "Oğlak burcu toprak elementine bağlı üç Zodyak burcundan biridir (diğerleri Boğa ve Başak’tır). Oğlak burcu üçüncü ve sonuncu toprak burcu olduğu için, Boğa burcunun kaya gibi sağlam temelleriyle Başak burcunun hünerli planlarını büyük bir binaya dönüştürerek dünyaya hükmedeceği bir yer haline getirir. Oğlaklar Zodyak’ın usta stratejistleridir, her zaman bir beş-on yıllık planları vardır. Oğlak burcu gezegen döngüsünün etkisi altındayken en büyük hedeflerimizi gerçekleştirmeye ve hayatımızda uzun süreli yapılar inşa etmeye istekli hale geliriz."
        "Oğlak burcu sadece maddi dünyaya odaklanmakla kalmaz, bu dünyayı kullanmayı da becerebilirler. Ne yazık ki toprak elementi onları aynı zamanda sert ve bazen de inatçı kılar; o kadar ki bir ilişkide başka bir perspektiften bakmayı beceremezler. Kendi kişiliklerinden çok farklı olan insanların farklılıklarını kabullenmekte zorlanır ve kendi geleneksel değerlerini dayatmaya çalışabilirler.",
    "Burçlar üç farklı niteliğe göre gruplanır: kardinal (öncü), değişken ve sabit burçlar. Kova burcu dört sabit burçtan biridir; diğer dört sabit burç ise Boğa, Aslan ve Akrep’tir. Bu burçlar her mevsimin ortasına denk gelir. Bunlar dengeleyici burçlardır; kendilerine bir amaç belirler ve sonra da inşa etmeye başlarlar. Öncü burçların öne attığı heyecanlı fikirleri alır, bunları somut bir şeye dönüştürürler."
        "Zodyak’ta hava grubuna ait üçüncü burç olan Kova burcu tıpkı diğer hava grubu burçları İkizler ve Terazi gibi oldukça zihinseldirler. Eğer zihinsel uyarım yoksa sıkılırlar ve motivasyonları düşer. Kova burcu üçüncü hava burcu olduğu için İkizler’in neşe rüzgarları ile Terazi’nin sevgi kelebeği havasını herkes için insancıl bir havaya dönüştürür."
        "Kovalar utangaç ve sessiz, diğer yandan eksantrik ve enerjik olabilirler. Ancak her durumda başkalarına yardım etmeyi severler ve olayları önyargısız bir biçimde değerlendirebilirler. Bu durum onları problemleri kolaylıkla çözebilen insanlar yapar. Kova burcu insanları kendilerini çevreleyen enerjiye ve kalabalıklara kolayca uyum sağlayabilmelerine rağmen ender olarak yalnız kalma ihtiyacı da hisseder. Kovalar dünyaya olasılıklarla dolu bir yer olarak bakar."
        "Kova burcu vizyonerliğini yönetici gezegeni Uranüs’ten alır. Yine Uranüs etkisiyle zaman zaman ürkek veya saldırgan olabilirler. Geleceği öngörebilir ve bundan beş yıl sonra ne yapmak istediklerini bilirler. Uranüs ayrıca onlara hızlı ve kolay dönüşüm becerisi de vermiştir. Bu sebeple “düşünür, ilerici ve hümanist” olarak bilinirler. Kova burcundaki insanlar topluluk içinde kendilerini iyi hisseder. Bu sayede çeşitli zihinsel çatışmalara girebilir, yeni şeylerden haberdar olabilirler. "
        "Kova burçları için en büyük zorluk kısıtlanma fikridir. Yalnız kendisi için değil herkes için özgürlük ve eşitlik isterler. Kovalar zaman zaman soğuk ve duyarsız olarak algılansalar da bu aslında haddinden önce başlayan yakınlıklara karşı bir savunma mekanizmasıdır. Başkalarına güvenmeyi ve duygularını samimi bir şekilde ifade etmeyi öğrenmelidirler.",
    "Burçlar üç farklı niteliğe göre gruplanır: kardinal (öncü), değişken ve sabit burçlar. Balık burcu dört değişken burçtan biridir (diğerleri İkizler, Yay ve Başak’tır). Değişken burçlar mevsimleri sona erdiren burçlardır ve her mevsimden dersler almışlardır. Her şeyin bir sonu olduğunu bilirler ve görevleri herkesi mevsim değişimine uyum sağlamalarına yardımcı olmaktır. Diğer burçlardan daha bilgedirler. Diğer burçlara göre değişime daha kolay ayak uydurabilirler; pek çok duruma uyum sağlamak için bukalemun gibi renk değiştirirler. Ayrıca Zodyak’ın düzeltmenidirler: Kardinaller bir plan öne sürer, sabitler planı eyleme döker, değişkenler ise eleştirel bir gözle son rötuşları yapar."
        "Balık burcu su elementine bağlı üç Zodyak burcundan biridir (diğerleri Yengeç ve Akrep’tir). Balık burcu üçüncü ve sonuncu su burcu olduğu için Yengeç’in duygu dalgalarını ve Akrep’in tazyikli sularını duyguların okyanusuna akıtır. Balık enerjisi aktif hale geldiğinde derinlere dalmaya hazır olun; Balık enerjisi şefkatimizi uyandırır, kalplerimizi acı çeken insanlara açmamızı sağlar. Balık burcu gezegen döngüsü sırasında bu enerjinin farkında olsak da olmasak da etrafımızdaki insanlarla sezgisel olarak bağlantı kurabiliriz. Ayrıca kendimizi yaratıcı yollarla ifade edebiliriz: Müzik, film, görsel sanatlar ve dans; tüm bunlar Balık’ın uzmanlık alanıdır."
  ];
}
